### ISSUE TITLE
Missing action PhpAction

### ISSUE THREAD

**Issue by venzen** [addiks/gedit-phpide#1]
Thanks for the plugin. I'm migrating to trusty Gedit for a lighter development environment. I assume I'm missing something basic, but phpide is not working for me.

Running from the terminal in Lubuntu 14.04 I get the following error:

```
Gtk-WARNING **: PhpMenu: missing action PhpAction
```
- Cloned this repo and copied the files to _~/.local/share/gedit/plugins/addiks-phpide/_
- Restarted Gedit and activated plugin
- Open a _.php_ file and no PHP menu item, only the error message above

I notice there is no mention of `PhpAction` in the rest of the plugin code. Is this perhaps a call to a function in a dependency package I'm missing?

**Comment by addiks** [comment]
You are not missing any dependency (at least not for this). This is an actual error in the code i made after upgrading my machine from 14.04 to 16.04 and added support for 3.12+ (which had a big UI overhaul). I had left the support for 3.10 in but didn't test it again becauase... Well it seems you are the first one to actually try it and what's the point in testing if nobody uses it anyway. Looks like i was wrong.
I have just pushed a fix which maybe fixes this, but i could not test it yet so it might not work. I am right now setting up a virtual machine with gedit 3.10 (Ubuntu 14.04) to confirm the fix.

**Comment by addiks** [comment]
So, i just tested it and the fix seems to work. It was just missing a label for the menu, but that is now also fixed. Please test it on your end and report if it now works for you also.
BTW: I have never had someone else beside me actually use this, so there may be some weird usability which has not yet occoured to me. I can think of the auto-complete from index which must be called explicitely using Ctrl+Space. (Auto-complete in most other programs are often actually completely automatic, which i hate because it constantly get's in my way.) If you don't like some of the stuff in there, maybe i could add configuration for that. Feedback is very welcome.
I can also give you a list of other gedit-plugins i use beside this which i have found to be very useful for PHP development, for example my other gedit-dbgp-debugger-plugin for debugging php.

**Comment by venzen** [comment]
@addiks, thank you for your response and the updated code. It works and works well. Great plugin.

I agree that auto-complete gets in the way most of the time, so this useability feature suits me.

Not sure why, but after I have built an index for my PHP project, and click "View Index" from the PHP menu, I see the following traceback in the terminal where i launched Gedit:

_Traceback (most recent call last):
  File "/home/venzen/.local/share/gedit/plugins/addiks-phpide/AddiksPhpIndexWindow.py", line 91, in on_open_type_view
    pluginView.on_open_type_view(action, data)
  File "/home/venzen/.local/share/gedit/plugins/addiks-phpide/AddiksPhpIndexView.py", line 242, in on_open_type_view
    if className[0] != '\':
UnboundLocalError: local variable 'className' referenced before assignment_

Looking at that code in _AddiksPhpIndexView.py_ it is clear that the following conditional is not setting `className` in this particular case.

```
if declarationType == 'class':
    className = name

elif containingClassName != None:
    className = containingClassName
```

I can fix that, do a Pull Request and then submit for merging, but I figured its best to let you do the fix, i can `git pull` and see how you like to code this kind of thing. I'm also getting other small errors, but I'm not in a hurry. Just enjoy being able to code (and debug - thanks to your debug plugin) PHP in Gedit rather than in klunky Eclipse! :)

Its been my lucky day - your Git plugin works out-of-the box and this completes my IDE requirements in Gedit. Many thanks. :8ball:

**Comment by addiks** [comment]
Great to hear that, thank you. :)

I have just pushed a small fix for the missing variable declaration. Please report if it is now fixed for you.
Somehow this never happened in my projects, but there are some things which i very rarely use (like normal php functions, my code is nearly completely inside of classes). So maybe there are more stumbling block's like this one. If you find more like that, just report back and i do my best to fix them when i have the time for it.

**Comment by venzen** [comment]
When I said "other small errors" I spoke too soon. They might be the cause of why the conditional mentioned above fails to set `className`.

When I activate the php-ide plugin the Gedit complains in the terminal:

_(gedit:25573): Gtk-WARNING **: Inserting action group 'AddiksPhpMenuActions' into UI manager which already has a group with this name_

I can then open a .php file and build its index from the PHP menu option. When I close the index window, Gedit says:

_(gedit:25573): Gtk-CRITICAL **: gtk_main_quit: assertion 'main_loops != NULL' failed_

After this, the PHP menu is still visible, but as soon as I click on a different tab, and then return to the .php file, the PHP menu does not show up again (no console error) and I have to re-enable the php-ide plugin which again outputs the first error above.

I realize this is unexpected support and coding for you, so no sweat. Have a look when you have time, or point me in a probable direction. I am unfamiliar with Gedit and Gtk development so unfortunately I don't know where to start troubleshooting.

**Comment by venzen** [comment]
I see the fix to _AddiksPhpIndexView.py_ - set an empty `className` and test that it's not empty before accessing its array contents. Great, that would have been my exact fix too. :)

**Comment by addiks** [comment]
Mhh, i think i have an idea on where this behavior with the vanishing php-menu might come from. The idea was that it only show's the menu's that make sense for the file that is open. The behavior with this in combination with tabs is probably wrong, because i do not use tabs.

A quick workaround may be to comment out the lines 62 to 65 in "AddiksPhpIndexWindow.py". I see if i can come up with a better fix for this, but that might take a while.

**Comment by venzen** [comment]
thanks @addiks, after commenting out the lines as you suggest, the PHP menu is now persistent and most menu items work as expected. 

"open type view" still doesn't work due to some other Gtk stuff - no doubt version differences between our OSses - but I can research and fix that. When I do, I'll create a Pull Request so you can take a look. 

For now everything works well enough for me to get on with coding. 

Thanks again, and have a great weekend!

**Comment by addiks** [comment]
I have just pushed new behaviour for when to hide or show the php menu. Can you please test this new version and report back if it now works for you? I have tested it in my Ubuntu 14.04 / gedit-3.10 virtual machine (with tabs enabled), and it seems to work fine now.

**Comment by addiks** [comment]
Is this still an issue for you? If so, please report back what issues you have and make sure to use the latest version. Otherwise i will close this issue in a few days if i don't hear back from you.
